### ISSUE TITLE
data example 

### ISSUE THREAD

**Issue by hhc99** [rvp-group/ca2lib#3]
Could you please provide some example data sets to help me run the calibration algorithm?

**Comment by EmanueleGiacomini** [comment]
Hi, thanks for reaching out 😁
We are currently off the lab but we Will release a test sequence in September.

In the meanwhile, feel free to post any doubts concerning the calibration procedure and we will try to answer them.
I suggest reading the [LiDAR-Camera](https://github.com/rvp-group/ca2lib/wiki/LiDAR%E2%80%90Camera-Calibration) wiki section to get better insights

**Comment by hhc99** [comment]
OK，thanks
---- Replied Message ----
From Emanuele ***@***.***> Date 08/14/2024 19:14 To ***@***.***> Cc ***@***.***>***@***.***> Subject Re: [rvp-group/ca2lib] data example (Issue #3) 
Hi, thanks for reaching out 😁
We are currently off the lab but we Will release a test sequence in September.
In the meanwhile, feel free to post any doubts concerning the calibration procedure and we will try to answer them.
I suggest reading the LiDAR-Camera wiki section to get better insights

**Comment by LeoBrizi** [comment]
Hi, sorry for the late reply.

I upload a test bag on [drive](https://drive.google.com/file/d/1y5HK-zKPJ2sqNEV3OnSf-2mMSIo_68iJ/view?usp=drive_link).
Try to run it on this data, and let us know if you have other issues.

**Comment by hhc99** [comment]
thks
